# Tags are used here for direct patching

[METHOD_START]


# Don't add anything or don't remove anything from here
# Just ignore this part


[METHOD_END]

[METHOD_CALL]

#Put this 👇 below onCreate
invoke-static/range {p0}, LHub/ରାଧେକୃଷ୍ଣ;->Mod(Landroid/content/Context;)V

[END_METHOD_CALL]

Copy above 👆mentioned code and paste the code in below onCreate or onResume or onStart or onActivityResult on your target activity..After that push all assets files (Inc. image, txt file anything but not the readme.txt file) which is generated by Modder Hub.. And remember it's necessary to do else app will crash after injection. If you don't know how to get target activity then you should view Maharna's Tech youtube videos.. Or you can join telegram group @Modder_Guys for help